### ISSUE TITLE
Code formatting and linting

### ISSUE THREAD

**Issue by JoseChungFOS** [yalla-coop/accountability#61]
As agreed at #37 we'll be using fairly standard **eslint** for linting and **prettier** for formatting

* [x] Configure eslint (see https://www.gatsbyjs.org/docs/eslint/)
* [x] Add and configure [prettier](https://www.gatsbyjs.org/docs/eslint/)
* [x] Leave issue open and we'll review setup and see if we're happy with the set of rules next week

**Comment by fadeomar** [comment]
I have installed the eslint and prettier , and we didn't find the eslint with gatsby so we had to install all the packages that we need to do configuration

**Comment by JoseChungFOS** [comment]
Closing for now as all seem happy with current config
