### ISSUE TITLE
pages Tittle component

### ISSUE THREAD

**Issue by fadeomar** [yalla-coop/accountability#79]
all pages have the same title style 
on the desktop the text-align form the left 
on mobile view  the text aligned in the center 

the same line under the text in both cases

Desktop : 
![advisory](https://i.ibb.co/dgKQZ6H/Screenshot-from-2020-03-08-10-48-36.png)
![case-stady](https://i.ibb.co/pjrGVrq/Screenshot-from-2020-03-08-10-48-18.png)
----
mobile :+1: 
![our-ofice](https://i.ibb.co/6nKqCmZ/Screenshot-from-2020-03-08-10-47-58.png)
![about-us](https://i.ibb.co/Fw91zZ8/Screenshot-from-2020-03-08-10-47-40.png)

**Comment by JoseChungFOS** [comment]
Done in #80
