### ISSUE TITLE
[component] Case study Cards 

### ISSUE THREAD

**Issue by fadeomar** [yalla-coop/accountability#83]
- small case study card 
    - **desktop view** : 
  ![small case study card ](https://i.ibb.co/CtNnN1b/Screenshot-from-2020-03-09-15-11-05.png )
    - **mobile view** : 
  ![ mobile view ](https://i.ibb.co/hBX7pBz/Screenshot-from-2020-03-09-15-14-13.png)

- large case study card 
    - **only for the desktop view** : 
  ![large case study card ](https://i.ibb.co/VDZBYNH/Screenshot-from-2020-03-09-15-16-13.png)

## There is 3 type of the case study cards containers
  1- vertical container like in the landing page : 
only contain small cards 
    ![](https://i.ibb.co/JxbP8Q1/Screenshot-from-2020-03-09-15-20-05.png)
  2- square container like in the case study page 
   contains large and small cards 
![](https://i.ibb.co/WBdFGz2/Screenshot-from-2020-03-09-15-22-44.png)
  3- divided container like in the mobile view : 
![](https://i.ibb.co/B2BNPYX/Screenshot-from-2020-03-09-15-24-40.png)

**Comment by JoseChungFOS** [comment]
Done in #84
